Fix Florence-2 beam search past_key_values issue
Change from beam search (num_beams=3) to greedy decoding (num_beams=1)
to avoid AttributeError: 'NoneType' object has no attribute 'shape'
This is a known issue with Florence-2 model's prepare_inputs_for_generation.